### PR TITLE
World Map Added

### PR DESCRIPTION
**Pull request by hugomosh**
Added world map

Extracted from low-resolution map: https://www.amcharts.com/svg-maps/?map=world

Tested

### CODE REVIEW

**Comment by hugomosh** [comment]
This time it fails beacuse 

```

 FAIL  __tests__/radio-svg-map.test.js
  ● Test suite failed to run
    TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'
      
      at exports.default (node_modules/jest-util/build/create_process_object.js:14:34)
 FAIL  __tests__/checkbox-svg-map.test.js
  ● Test suite failed to run
    TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'
      
      at exports.default (node_modules/jest-util/build/create_process_object.js:14:34)
 FAIL  __tests__/svg-map.test.js
  ● Test suite failed to run
    TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>'
      
      at exports.default (node_modules/jest-util/build/create_process_object.js:14:34)
```

Related: https://github.com/facebook/jest/issues/8069

**Comment by VictorCazanave** [comment]
Thanks @hugomosh 😃 
I'll review it and fix the Jest bug this weekend

**Comment by VictorCazanave** [comment]
The new version of Node fixed the issue.

However as written in the [contributing section](https://github.com/VictorCazanave/react-svg-map/blob/master/CONTRIBUTING.md), could you add:
- a simple snapshot test (like the one of Utah)
- the map with the list of locations (countries) in the [maps section of README](https://github.com/VictorCazanave/react-svg-map#maps)

In my test, the right part of Russia looks cropped. Do you have the same issue?

Screen Shot 2019-03-16 at 6 10 32 PM

**Comment by hugomosh** [comment]
> The new version of Node fixed the issue.
> 
> However as written in the [contributing section](https://github.com/VictorCazanave/react-svg-map/blob/master/CONTRIBUTING.md), could you add:
> 
> * a simple snapshot test (like the one of Utah)
> * the map with the list of locations (countries) in the [maps section of README](https://github.com/VictorCazanave/react-svg-map#maps)
> 
> In my test, the right part of Russia looks cropped. Do you have the same issue?
> 
> Screen Shot 2019-03-16 at 6 10 32 PM

Oh I see Russia cropped, my bad. It is the view port, I need to adjust it right to also not have whitespace.
Sure, I will write the information.

Thank you for the time spent.

**Comment by VictorCazanave** [comment]
@hugomosh since v2.0.0 the maps have been moved to another package.
So if you still want to add the world map, could you re-create this PR on [v1 branch](https://github.com/VictorCazanave/react-svg-map/tree/v1) or create a new one on [svg-maps](https://github.com/VictorCazanave/svg-maps/) please?

**Pull request closed without merging**
