### PR TITLE
react 17 update

### PR DESCRIPTION
**Pull request by RamonDonnell**
Dependency and jest setup update for react 17.
Uses unofficial [@wojtekmaj/enzyme-adapter-react-17](https://github.com/wojtekmaj/enzyme-adapter-react-17)

https://github.com/VictorCazanave/react-svg-map/issues/53

- [x] Fork the repository
- [x] Develop your code changes
- [x] Ensure eslint is happy: npm run lint
- [x] Ensure the tests pass: npm test
- [x] Commit your changes
- [x] Push to your fork
- [x] Submit a pull request

### CODE REVIEW

**Comment by VictorCazanave** [comment]
Thanks for your contribution @RamonDonnell ! 😃 

Does it solve the issue https://github.com/VictorCazanave/react-svg-map/issues/53?
If yes, since the components aren't modified, can't we just update the peerDependencies to support both React 16 and 17 (`^16.0.0 || ^17.0.0`)? 🤔

**Comment by sdnalloh** [comment]
Please resolve and merge this pull request.
I'd like to use react-svg-map with react-17, and I'm sure many other people would too.

**Comment by piotrgregor** [comment]
Yes, other people too ;p
Can this be merged please.

**Comment by VictorCazanave** [comment]
As mentioned in https://github.com/VictorCazanave/react-svg-map/issues/53, I didn't see any issue using these components with React 17. 
So @sdnalloh @piotrgregor what do you need exactly? Only updating the peer dependencies to also support React 17?
If there is an issue with React 17, please provide a repository with a minimal example to reproduce it.

**Comment by VictorCazanave** [comment]
Thanks again for your contribution @RamonDonnell, but stopping React 16 support is a major change that will be done in the v3

**Pull request closed without merging**
